config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'posts#index'
  resources :posts, only: [ :index, :new, :create ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </nav>

    <p class="notice text-success"><%= notice %></p>
    <p class="alert text-danger"><%= alert %></p>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/index.html.erb
<h2>Posts</h2>

<% if user_signed_in? %>
    <%= link_to "Create New Post", new_post_path %>
<% end %>


<div class="row bootstrap snippets">
  <div class="col-md-6 col-md-offset-2 col-sm-12">
    <div class="comment-wrapper">
      <ul class="media-list">
        <% @posts.each do |p| %>
          <li class="media">
            <div class="media-body">
              <strong> <%= p.title %></strong><br />
              <div class="text-secondary">
                <% if user_signed_in? %>
                  <%= p.user.email %>
                <% end %>
              </div>
              <p>
                <%= p.body %>
              </p>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h2> New Post </h2>

<div class="form-container">
  <%= form_for @post do |p| %>
    <div class="form-group">
      <%= p.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Content", class: "form-control"%>
    </div>
    <div class="form-group">
      <%= p.submit "Create" %>
    </div>
  <% end %>
</div>